Repository AY2425S1-CS2103-F09-3/tp, pull requests merged in 2024-11, with the labels that each got.

#218 Edit Parser Functionality of Sort Command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/JobCode.java
Labels: alpha-bug

#230 Replace Talency with Talentcy
  README.md
  build.gradle
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#229 Tweak Job Code and Tag Validation
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/JobCode.java
  src/main/java/seedu/address/model/person/Tag.java
  src/test/java/seedu/address/model/person/JobCodeTest.java
Labels: alpha-bug

#238 Fix ug
  docs/UserGuide.md
Labels: alpha-bug

#243 Fix case insensitivity in command and prefix
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Labels: alpha-bug, bugType.FeatureFlaw

#242 Fix commands that do not accept arguments
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: alpha-bug

#241 Add sort into UG
  docs/UserGuide.md
Labels: alpha-bug, bugType.DocumentationBug

#259 Update user guide to include info of sorting by tag
  .gitignore
  docs/UserGuide.md
Labels: alpha-bug, bugType.DocumentationBug

#265 Enhance message, UG, and UI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/person/JobCode.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: alpha-bug, bugType.FeatureFlaw, bugType.DocumentationBug

#268 Edit preferences.json
  preferences.json
Labels: alpha-bug
