Repository AY2425S1-CS2103-F09-3/tp, pull requests merged in 2024-09, with the labels that each got.

#14 Add Hera's photo
  docs/images/hazzle23.png
Labels: type.Chore

#15 Add Hans' Photo
  docs/images/hansneddyanto.png
Labels: type.Chore

#19 Add SekYi's photo
  docs/images/chinsekyi.png
Labels: priority.Medium

#23 Update About Us SekYi
  docs/AboutUs.md
Labels: type.Chore, priority.Medium

#27 Update Hera's AboutUs
  docs/AboutUs.md
Labels: type.Chore
